server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UGgl233/smartTimeSheetCloudConfig.git
          clone-on-start: true
          skip-ssl-validation: true
